Leitura usuário
mabemoreira/LearningPath pull request #27
Opened 2024-09-22 04:16 UTC by Henrique-hpds

Leitura do usuário a partir do id e implementação de testes.

2024-09-22 05:31 UTC, THdeCamargoJ requested changes
Existe um número significativo de alterações que eu faria, melhor conversarmos antes de fazer finalizar esse pull request.

2024-09-22 05:32 UTC, THdeCamargoJ commented on backend/src/controllers/custom_user_controller.py
> +            retorno = read_user(int(request.body))
O id não virá no body, ele virá através de parâmetro via URL.

2024-09-22 05:33 UTC, THdeCamargoJ commented on backend/src/services/custom_user_service.py
> +        return -1
Quebra de contrato. Se o retorno da função está para dict, então não poderia retornar um inteiro no final.

2024-09-22 05:36 UTC, THdeCamargoJ commented on backend/src/tests/test_user_service.py
> +            if retorno != -1:
O teste não faz o que propõe. Se nenhum usuário é encontrado, o get não está fazendo o seu trabalho - já que eles foram adicionados nas linhas acima -, mas ainda assim o teste vai passar por conta do if.

2024-09-24 04:43 UTC, THdeCamargoJ approved these changes
Boa! Obrigado, @Henrique-hpds.

2024-09-24 12:52 UTC, mabemoreira approved these changes
Agora ficou mais limpo o código! Por mim pode dar merge

2024-09-24 12:55 UTC, merged